version: 0.2
phases:
 install:
   runtime-versions:
     python: 3.9
   commands:
     - pip install --upgrade aws-sam-cli
 pre_build:
   commands:
     - echo "Starting build process"
 build:
   commands:
     - echo "Building SAM application"
     - sam build
     - echo "Packaging SAM application"
     - sam package --s3-bucket sam-cicd-artifacts-bucket --output-template-file packaged.yaml
artifacts:
 files:
   - packaged.yaml